// Golden test for the A/V-split IR foundation (DESIGN-UI.md §"Appendix: modeling
// linked A/V"). This locks the wire shape of the two new, orthogonal concepts the
// split needs — the PER-PRODUCER stream selectors and the TYPED clip link — and,
// just as load-bearing, proves they are ABSENT-BY-DEFAULT: an existing corpus file
// carries neither field and round-trips byte-identically (the determinism
// invariant the whole IR rests on).
//
// The fixture is Shotcut's "Detach Audio" shape, but with vean's typed link where
// Shotcut has only a loose group int: one media file (/abs/interview.mp4) split
// into a VIDEO-ONLY clip (audio off: audio_index=-1 + astream=-1) on a video track
// and an AUDIO-ONLY clip (video off: video_index=-1 + vstream=-1) on an audio
// track, the two joined by a shared `link.id`. `shotcut:defaultAudioIndex` rides on
// the video-only half for reattach.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  type Clip,
  LANDSCAPE_2997,
  type Timeline,
  audioTrack,
  clip,
  fromMlt,
  hasAudio,
  resetIds,
  timeline,
  toMlt,
  videoTrack,
} from "../src/index";

const VID_ID = "clip-video";
const AUD_ID = "clip-audio";
const LINK_ID = "link-av-0";

// The A/V-split fixture — rebuilt from scratch each call (resetIds) so id
// assignment is a pure function of the IR (the determinism contract).
function fixture(): Timeline {
  resetIds();
  return timeline(LANDSCAPE_2997, {
    video: [
      videoTrack(
        clip("/abs/interview.mp4", {
          id: VID_ID,
          in: 0,
          out: 89,
          // Video-only half: absolute + relative audio selectors both off (Shotcut
          // sets both, since the relative overrides). Reattach hint preserved.
          streams: { audioIndex: -1, astream: -1, defaultAudioIndex: 1 },
          link: { id: LINK_ID, role: "video", partnerIds: [AUD_ID] },
        }),
      ),
    ],
    audio: [
      audioTrack(
        clip("/abs/interview.mp4", {
          id: AUD_ID,
          in: 0,
          out: 89,
          // Audio-only half: absolute + relative video selectors both off.
          streams: { videoIndex: -1, vstream: -1 },
          link: { id: LINK_ID, role: "audio", partnerIds: [VID_ID] },
        }),
      ),
    ],
  });
}

// The locked byte-exact serialization. The typed link is a single `vean:link` JSON
// `<property>` on each entry (the cut); the stream selectors are producer
// `<property>` children in the fixed schema order (audio_index, video_index,
// astream, vstream, shotcut:defaultAudioIndex). The link JSON is XML-escaped
// (`&quot;`) so the document stays well-formed + namespace-clean (Shotcut-openable).
const GOLDEN = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by vean (src/ir/serialize). Edit the IR and re-serialize,
     not this file. Safe to open in Shotcut — it round-trips losslessly. -->
<mlt LC_NUMERIC="C" version="7.38.0" root="" title="vean timeline">
  <profile description="landscape-1920x1080-2997" width="1920" height="1080" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="16" display_aspect_den="9" frame_rate_num="30000" frame_rate_den="1001" colorspace="709"/>
  <producer id="producer2" in="0" out="89">
    <property name="length">90</property>
    <property name="mlt_service">color</property>
    <property name="resource">0</property>
    <property name="shotcut:uuid">{vean-producer2}</property>
  </producer>
  <producer id="producer0" in="0" out="89">
    <property name="resource">/abs/interview.mp4</property>
    <property name="shotcut:uuid">clip-video</property>
    <property name="audio_index">-1</property>
    <property name="astream">-1</property>
    <property name="shotcut:defaultAudioIndex">1</property>
  </producer>
  <producer id="producer1" in="0" out="89">
    <property name="resource">/abs/interview.mp4</property>
    <property name="shotcut:uuid">clip-audio</property>
    <property name="video_index">-1</property>
    <property name="vstream">-1</property>
  </producer>
  <playlist id="playlist0">
    <property name="shotcut:video">1</property>
    <property name="shotcut:audio">0</property>
    <property name="shotcut:name">V1</property>
    <entry producer="producer0" in="0" out="89">
      <property name="vean:link">{&quot;id&quot;:&quot;link-av-0&quot;,&quot;role&quot;:&quot;video&quot;,&quot;partnerIds&quot;:[&quot;clip-audio&quot;]}</property>
    </entry>
  </playlist>
  <playlist id="playlist1">
    <property name="shotcut:video">0</property>
    <property name="shotcut:audio">1</property>
    <property name="shotcut:name">A1</property>
    <entry producer="producer1" in="0" out="89">
      <property name="vean:link">{&quot;id&quot;:&quot;link-av-0&quot;,&quot;role&quot;:&quot;audio&quot;,&quot;partnerIds&quot;:[&quot;clip-video&quot;]}</property>
    </entry>
  </playlist>
  <tractor id="tractor0" shotcut="1" title="vean timeline">
    <track producer="producer2"/>
    <track producer="playlist0"/>
    <track producer="playlist1" hide="video"/>
  </tractor>
</mlt>
`;

describe("A/V split — the stream selectors + typed link wire shape (golden)", () => {
  it("serializes the detached A/V pair byte-for-byte", () => {
    expect(toMlt(fixture())).toBe(GOLDEN);
  });

  it("is deterministic — same IR ⇒ byte-identical XML, rebuilt from scratch", () => {
    expect(toMlt(fixture())).toBe(toMlt(fixture()));
  });

  it("round-trips byte-identically through parse → serialize", () => {
    const xml = toMlt(fixture());
    expect(toMlt(fromMlt(xml))).toBe(xml);
  });
});

describe("A/V split — the typed fields survive parse", () => {
  function parsedHalves(): { video: Clip; audio: Clip } {
    const back = fromMlt(toMlt(fixture()));
    const video = back.tracks.video[0]?.items[0];
    const audio = back.tracks.audio[0]?.items[0];
    if (video?.kind !== "clip" || audio?.kind !== "clip") {
      throw new Error("fixture halves did not parse back as clips");
    }
    return { video, audio };
  }

  it("recovers the video-only stream selectors (audio off) + reattach hint", () => {
    const { video } = parsedHalves();
    expect(video.streams).toEqual({ audioIndex: -1, astream: -1, defaultAudioIndex: 1 });
    expect(video.link).toEqual({ id: LINK_ID, role: "video", partnerIds: [AUD_ID] });
  });

  it("recovers the audio-only stream selectors (video off)", () => {
    const { audio } = parsedHalves();
    expect(audio.streams).toEqual({ videoIndex: -1, vstream: -1 });
    expect(audio.link).toEqual({ id: LINK_ID, role: "audio", partnerIds: [VID_ID] });
  });

  it("derives hasAudio from the selectors — off on the video-only half, on for audio-only", () => {
    const { video, audio } = parsedHalves();
    expect(hasAudio(video)).toBe(false); // audio_index=-1 (+ astream=-1) → audio off
    expect(hasAudio(audio)).toBe(true); // no audio selector → default audio on
  });

  it("links the two halves iff they share link.id", () => {
    const { video, audio } = parsedHalves();
    expect(video.link?.id).toBe(audio.link?.id);
    expect(video.link?.partnerIds).toContain(AUD_ID);
    expect(audio.link?.partnerIds).toContain(VID_ID);
  });
});

// The load-bearing half of the change: an EXISTING corpus file with no selectors
// and no link is UNAFFECTED by their addition. Two guards:
//
//   • A `vean-*` corpus file is vean's OWN emission, so it round-trips
//     BYTE-IDENTICALLY to disk (the strong determinism contract). This is the
//     direct proof that the new fields add ZERO bytes when absent — if either
//     serialized to a single byte when unset, this byte-identity would break.
//   • A real Shotcut-authored file (`shotcut-single.mlt`) that carries no selectors
//     parses with every clip's `streams`/`link` undefined, and its re-emission
//     contains no `vean:link` and no stream-selector property.
//
// (`shotcut-multitrack.mlt` is intentionally NOT used here: it carries genuine
// `audio_index=0`/`video_index=-1` selectors on its tone.wav clip, which vean now
// — correctly — models structurally. That is the feature working, not a regression.)
const CORPUS = join(import.meta.dirname, "..", "corpus");

function allClips(tl: Timeline): Clip[] {
  const clips: Clip[] = [];
  for (const track of [...tl.tracks.video, ...tl.tracks.audio]) {
    for (const item of track.items) if (item.kind === "clip") clips.push(item);
  }
  return clips;
}

describe("A/V split — vean's own corpus emission is byte-identical (zero bytes when absent)", () => {
  const onDisk = readFileSync(join(CORPUS, "vean-multitrack.mlt"), "utf8");

  it("round-trips byte-identically — the new fields serialize to nothing when unset", () => {
    expect(toMlt(fromMlt(onDisk))).toBe(onDisk);
  });

  it("carries no A/V-split bytes at all", () => {
    expect(onDisk).not.toContain("vean:link");
    expect(onDisk).not.toContain("astream");
    expect(onDisk).not.toContain("vstream");
    expect(onDisk).not.toContain("audio_index");
    expect(onDisk).not.toContain("video_index");
    for (const c of allClips(fromMlt(onDisk))) {
      expect(c.streams).toBeUndefined();
      expect(c.link).toBeUndefined();
    }
  });
});

describe("A/V split — a real Shotcut file with no selectors is unaffected", () => {
  const onDisk = readFileSync(join(CORPUS, "shotcut-single.mlt"), "utf8");

  it("every clip parses with no stream selectors and no link", () => {
    const clips = allClips(fromMlt(onDisk));
    expect(clips.length).toBeGreaterThan(0);
    for (const c of clips) {
      expect(c.streams).toBeUndefined();
      expect(c.link).toBeUndefined();
    }
  });

  it("its re-emission introduces no A/V-split bytes", () => {
    const emitted = toMlt(fromMlt(onDisk));
    expect(emitted).not.toContain("vean:link");
    expect(emitted).not.toContain("astream");
    expect(emitted).not.toContain("vstream");
    // Re-emission is a stable fixpoint (the normalized-round-trip contract the
    // corpus gate guards), so the new fields don't perturb its convergence.
    expect(toMlt(fromMlt(emitted))).toBe(emitted);
  });
});
