// Tests for the IR → .mlt serializer (`toMlt`). The serializer is a FORMAT
// CONTRACT — its output is read by melt and by Shotcut, and the parser is its
// exact inverse — so it is golden-tested: one representative timeline exercising
// every shape (multi video + audio tracks, head/tail fades, a same-track
// dissolve, a windowed file clip, blanks, gain, a verbatim animation-string
// filter, a field transition) is locked byte-for-byte, and targeted assertions
// pin each AUTHORITATIVE MLT FACT so a regression names which contract it broke.
import { describe, expect, it } from "vitest";
import {
  LANDSCAPE_2997,
  type Timeline,
  VERTICAL,
  audioTrack,
  blank,
  clip,
  colorClip,
  dissolve,
  filter,
  resetIds,
  timeline,
  toMlt,
  transition,
  videoTrack,
} from "../src/index";

// ── The representative timeline (the golden fixture) ──
// Rebuilt from scratch each call (with resetIds) so id assignment is a pure
// function of the IR — the determinism contract.
function fixture(): Timeline {
  resetIds();
  return timeline(
    VERTICAL,
    {
      video: [
        videoTrack(colorClip(45, "black", { fadeIn: 12 }), dissolve(20), colorClip(60, "gold")),
        videoTrack(blank(10), clip("/abs/overlay.mp4", { in: 20, out: 79, fadeOut: 15 })),
      ],
      audio: [
        audioTrack(
          clip("/abs/vo.wav", {
            dur: 125,
            gain: 0.8,
            filters: [filter("brightness", { level: "0=0;14=1" })],
          }),
        ),
      ],
    },
    { transitions: [transition("qtblend", 1, 2, 0, 59, { compositing: 0 })] },
  );
}

const GOLDEN = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by vean (src/ir/serialize). Edit the IR and re-serialize,
     not this file. Safe to open in Shotcut — it round-trips losslessly. -->
<mlt LC_NUMERIC="C" version="7.38.0" root="" title="vean timeline">
  <profile description="vertical-1080x1920-30" width="1080" height="1920" progressive="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="9" display_aspect_den="16" frame_rate_num="30" frame_rate_den="1" colorspace="709"/>
  <producer id="producer6" in="0" out="124">
    <property name="length">125</property>
    <property name="mlt_service">color</property>
    <property name="resource">0</property>
    <property name="shotcut:uuid">{vean-producer6}</property>
  </producer>
  <producer id="producer0" in="0" out="24">
    <property name="length">25</property>
    <property name="mlt_service">color</property>
    <property name="resource">#FF000000</property>
    <property name="shotcut:uuid">{vean-producer0}</property>
    <filter mlt_service="brightness" shotcut:filter="fadeInBrightness">
      <property name="level">0=0;11=1</property>
    </filter>
  </producer>
  <producer id="producer1" in="25" out="44">
    <property name="length">45</property>
    <property name="mlt_service">color</property>
    <property name="resource">#FF000000</property>
    <property name="shotcut:uuid">{vean-producer1}</property>
  </producer>
  <producer id="producer2" in="0" out="19">
    <property name="length">60</property>
    <property name="mlt_service">color</property>
    <property name="resource">#FFFFD700</property>
    <property name="shotcut:uuid">{vean-producer2}</property>
  </producer>
  <producer id="producer3" in="0" out="39">
    <property name="length">40</property>
    <property name="mlt_service">color</property>
    <property name="resource">#FFFFD700</property>
    <property name="shotcut:uuid">{vean-producer3}</property>
  </producer>
  <producer id="producer4" in="20" out="79">
    <property name="resource">/abs/overlay.mp4</property>
    <property name="shotcut:uuid">{vean-producer4}</property>
  </producer>
  <producer id="producer5" in="0" out="124">
    <property name="resource">/abs/vo.wav</property>
    <property name="shotcut:uuid">{vean-producer5}</property>
    <filter mlt_service="volume" shotcut:filter="volume">
      <property name="gain">0.8</property>
    </filter>
    <filter mlt_service="brightness">
      <property name="level">0=0;14=1</property>
    </filter>
  </producer>
  <tractor id="tractor1">
    <track producer="producer4" in="20" out="79"/>
    <filter mlt_service="brightness" shotcut:filter="fadeOutBrightness">
      <property name="level">45=1;59=0</property>
    </filter>
  </tractor>
  <tractor id="tractor0" shotcut:transition="lumaMix">
    <track producer="producer1" in="25" out="44"/>
    <track producer="producer2" in="0" out="19"/>
    <transition mlt_service="luma" in="0" out="19">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
    </transition>
    <transition mlt_service="mix" in="0" out="19">
      <property name="a_track">0</property>
      <property name="b_track">1</property>
      <property name="sum">1</property>
    </transition>
  </tractor>
  <playlist id="playlist0">
    <property name="shotcut:video">1</property>
    <property name="shotcut:audio">0</property>
    <property name="shotcut:name">V1</property>
    <entry producer="producer0" in="0" out="24"/>
    <entry producer="tractor0" in="0" out="19"/>
    <entry producer="producer3" in="0" out="39"/>
  </playlist>
  <playlist id="playlist1">
    <property name="shotcut:video">1</property>
    <property name="shotcut:audio">0</property>
    <property name="shotcut:name">V2</property>
    <blank length="10"/>
    <entry producer="tractor1" in="0" out="59"/>
  </playlist>
  <playlist id="playlist2">
    <property name="shotcut:video">0</property>
    <property name="shotcut:audio">1</property>
    <property name="shotcut:name">A1</property>
    <entry producer="producer5" in="0" out="124"/>
  </playlist>
  <tractor id="tractor2" shotcut="1" title="vean timeline">
    <track producer="producer6"/>
    <track producer="playlist0"/>
    <track producer="playlist1"/>
    <track producer="playlist2" hide="video"/>
    <transition id="transition0" mlt_service="qtblend" in="0" out="59">
      <property name="a_track">1</property>
      <property name="b_track">2</property>
      <property name="compositing">0</property>
    </transition>
  </tractor>
</mlt>
`;

describe("toMlt — the golden format contract", () => {
  it("serializes the representative timeline byte-for-byte", () => {
    expect(toMlt(fixture())).toBe(GOLDEN);
  });
});

describe("toMlt — determinism (a hard requirement)", () => {
  it("same IR ⇒ byte-identical XML, run twice", () => {
    expect(toMlt(fixture())).toBe(toMlt(fixture()));
  });
  it("rebuilding the IR from scratch is also identical (no hidden global state)", () => {
    const a = toMlt(fixture());
    const b = toMlt(fixture());
    const c = toMlt(fixture());
    expect(a).toBe(b);
    expect(b).toBe(c);
  });
});

describe("toMlt — the MLT facts", () => {
  it("<profile> is the first <mlt> child with a RATIONAL frame rate", () => {
    resetIds();
    const xml = toMlt(timeline(LANDSCAPE_2997, { video: [videoTrack(colorClip(30, "white"))] }));
    // 29.97 = 30000/1001, never the float 29.97.
    expect(xml).toContain('frame_rate_num="30000" frame_rate_den="1001"');
    expect(xml).not.toContain("29.97");
    // First child after the <mlt> open line is the <profile>.
    const afterMlt = xml.slice(xml.indexOf("<mlt "));
    const firstChild = afterMlt.split("\n").find((l) => l.trim().startsWith("<profile"));
    const firstNonMlt = afterMlt
      .split("\n")
      .slice(1)
      .find((l) => l.trim().startsWith("<"));
    expect(firstNonMlt).toBe(firstChild);
  });

  it("stamps LC_NUMERIC=C and emits dot-decimals", () => {
    resetIds();
    const xml = toMlt(
      timeline(VERTICAL, { audio: [audioTrack(clip("/a.wav", { dur: 10, gain: 0.5 }))] }),
    );
    expect(xml).toContain('LC_NUMERIC="C"');
    expect(xml).toContain('<property name="gain">0.5</property>');
    expect(xml).not.toMatch(/0,5/); // never a comma decimal
  });

  it("two passes: every leaf producer/playlist precedes the main tractor that refs it", () => {
    const xml = toMlt(fixture());
    const mainTractor = xml.indexOf('<tractor id="tractor2"');
    // Every leaf producer + playlist definition appears before the main tractor.
    for (const id of ["producer0", "producer6", "playlist0", "playlist2", "tractor0", "tractor1"]) {
      const defIdx = xml.indexOf(`id="${id}"`);
      expect(defIdx, `${id} defined`).toBeGreaterThan(-1);
      expect(defIdx, `${id} defined before main tractor`).toBeLessThan(mainTractor);
    }
    // And the main tractor references them (a track or entry by id).
    const tail = xml.slice(mainTractor);
    expect(tail).toContain('<track producer="playlist0"/>');
  });

  it("in/out are inclusive 0-based with a SEPARATE length (playtime = out-in+1)", () => {
    resetIds();
    // A 30-frame color clip → in=0 out=29 (playtime 30) length=30.
    const xml = toMlt(timeline(VERTICAL, { video: [videoTrack(colorClip(30, "gold"))] }));
    expect(xml).toMatch(/<producer id="producer0" in="0" out="29">/);
    expect(xml).toContain('<property name="length">30</property>');
  });

  it("gaps are literal <blank length=N> entries", () => {
    const xml = toMlt(fixture());
    expect(xml).toContain('<blank length="10"/>');
  });

  it("a same-track dissolve is a nested lumaMix tractor (luma + mix sum=1 over [0,dur-1])", () => {
    const xml = toMlt(fixture());
    expect(xml).toContain('<tractor id="tractor0" shotcut:transition="lumaMix">');
    expect(xml).toContain('<transition mlt_service="luma" in="0" out="19">');
    expect(xml).toContain('<transition mlt_service="mix" in="0" out="19">');
    expect(xml).toContain('<property name="sum">1</property>');
    // The outgoing tail is the last 20 frames of the 45f black clip: in=25 out=44.
    expect(xml).toContain('<track producer="producer1" in="25" out="44"/>');
    // The incoming head is the first 20 frames of the 60f gold clip: in=0 out=19.
    expect(xml).toContain('<track producer="producer2" in="0" out="19"/>');
  });

  it("a custom dissolve luma service is honored", () => {
    resetIds();
    const xml = toMlt(
      timeline(VERTICAL, {
        video: [videoTrack(colorClip(30, "black"), dissolve(10, "luma02"), colorClip(30, "gold"))],
      }),
    );
    expect(xml).toContain('<transition mlt_service="luma02"');
  });

  it("a field transition lives on the MAIN tractor with INTEGER a_track/b_track", () => {
    const xml = toMlt(fixture());
    const main = xml.slice(xml.indexOf('<tractor id="tractor2"'));
    expect(main).toContain('<transition id="transition0" mlt_service="qtblend" in="0" out="59">');
    expect(main).toContain('<property name="a_track">1</property>');
    expect(main).toContain('<property name="b_track">2</property>');
    // The user's extra property is emitted AFTER the index refs.
    expect(main).toContain('<property name="compositing">0</property>');
  });

  it("background producer sits at main-track 0 (black, stretched full length)", () => {
    const xml = toMlt(fixture());
    const main = xml.slice(xml.indexOf('<tractor id="tractor2"'));
    // The first <track> in the main tractor is the background producer.
    const firstTrack = main.split("\n").find((l) => l.trim().startsWith("<track"));
    expect(firstTrack).toContain('producer="producer6"');
    // It is a full-length color "0" producer. Longest track here is 125f (audio).
    expect(xml).toMatch(/<producer id="producer6" in="0" out="124">/);
    expect(xml).toContain('<property name="resource">0</property>');
  });

  it("audio tracks are hidden video (hide=video) with shotcut:audio hints", () => {
    const xml = toMlt(fixture());
    expect(xml).toContain('<track producer="playlist2" hide="video"/>');
    const audioPl = xml.slice(xml.indexOf('<playlist id="playlist2"'));
    expect(audioPl).toContain('<property name="shotcut:audio">1</property>');
    expect(audioPl).toContain('<property name="shotcut:name">A1</property>');
  });
});

describe("toMlt — fades anchor to the 0-based played window", () => {
  it("a fadeIn on a 0-based (color) clip rides on the producer, keyframed over the played head", () => {
    const xml = toMlt(fixture());
    // 12-frame fadeIn on a 45f clip → brightness level 0=0;11=1 ON the producer.
    const p0 = xml.slice(xml.indexOf('<producer id="producer0"'));
    expect(p0).toContain('mlt_service="brightness" shotcut:filter="fadeInBrightness"');
    expect(p0).toContain('<property name="level">0=0;11=1</property>');
  });

  it("a fadeOut on a WINDOWED file clip is wrapped in a 0-based tractor (proven anchoring)", () => {
    const xml = toMlt(fixture());
    // overlay.mp4 plays [20,79] (60f) with a 15f fadeOut. The producer keeps its
    // window; the fade lives on a wrapping tractor over a 0-based domain:
    // 45=1;59=0 (ramp over the LAST 15 of 60 frames, 0-based).
    const wrap = xml.slice(xml.indexOf('<tractor id="tractor1">'));
    expect(wrap).toContain('<track producer="producer4" in="20" out="79"/>');
    expect(wrap).toContain('mlt_service="brightness" shotcut:filter="fadeOutBrightness"');
    expect(wrap).toContain('<property name="level">45=1;59=0</property>');
    // The entry references the WRAPPER, 0-based.
    expect(xml).toContain('<entry producer="tractor1" in="0" out="59"/>');
  });

  it("a file clip already playing from source 0 with a fade keeps the fade on the producer", () => {
    resetIds();
    const xml = toMlt(
      timeline(VERTICAL, {
        video: [videoTrack(clip("/abs/a.mp4", { in: 0, out: 59, fadeIn: 10 }))],
      }),
    );
    // in=0 → no wrapper needed; the fade sits on the producer.
    expect(xml).toContain('<producer id="producer0" in="0" out="59">');
    const p0 = xml.slice(xml.indexOf('<producer id="producer0"'));
    expect(p0).toContain('<property name="level">0=0;9=1</property>');
    expect(xml).not.toContain('<tractor id="tractor0">'); // no fade-wrapper tractor
  });

  it("rejects fades longer than the played window", () => {
    resetIds();
    expect(() =>
      toMlt(
        timeline(VERTICAL, {
          video: [videoTrack(colorClip(10, "black", { fadeIn: 8, fadeOut: 8 }))],
        }),
      ),
    ).toThrow(/exceed/);
  });
});

describe("toMlt — audio gain + verbatim animation strings", () => {
  it("clip gain (≠1) compiles to a static volume filter (no = → not animated)", () => {
    const xml = toMlt(fixture());
    const p5 = xml.slice(xml.indexOf('<producer id="producer5"'));
    expect(p5).toContain('<filter mlt_service="volume" shotcut:filter="volume">');
    expect(p5).toContain('<property name="gain">0.8</property>');
  });

  it("an animated filter property is emitted VERBATIM (the = keeps it animated)", () => {
    const xml = toMlt(fixture());
    // The escape-hatch brightness filter on the VO clip carries "0=0;14=1"
    // unchanged — the serializer never re-formats an animation string.
    const p5 = xml.slice(xml.indexOf('<producer id="producer5"'));
    expect(p5).toContain('<property name="level">0=0;14=1</property>');
  });

  it("unity gain (1) emits NO volume filter", () => {
    resetIds();
    const xml = toMlt(
      timeline(VERTICAL, { audio: [audioTrack(clip("/a.wav", { dur: 30, gain: 1 }))] }),
    );
    expect(xml).not.toContain('mlt_service="volume"');
  });
});

describe("toMlt — validation (deterministic, before any XML)", () => {
  it("rejects a malformed IR in zod before doing any work", () => {
    const bad = fixture();
    // Clone the profile + fps before corrupting it — VERTICAL is a SHARED module
    // constant, so mutating it in place would poison every later test.
    bad.profile = { ...bad.profile, fps: [bad.profile.fps[0], -1] as [number, number] };
    expect(() => toMlt(bad)).toThrow();
  });

  it("rejects a dissolve not flanked by two clips", () => {
    resetIds();
    const tl = timeline(VERTICAL, { video: [videoTrack(colorClip(30, "gold"), dissolve(10))] });
    expect(() => toMlt(tl)).toThrow(/must be followed by a clip/);
  });

  it("rejects a dissolve longer than an adjacent clip", () => {
    resetIds();
    const tl = timeline(VERTICAL, {
      video: [videoTrack(colorClip(30, "gold"), dissolve(40), colorClip(30, "black"))],
    });
    expect(() => toMlt(tl)).toThrow(/longer than/);
  });

  it("an empty timeline still emits a valid doc with a 1-frame background", () => {
    resetIds();
    const xml = toMlt(timeline(VERTICAL, {}));
    expect(xml).toContain('LC_NUMERIC="C"');
    expect(xml).toMatch(/<producer id="producer0" in="0" out="0">/);
    expect(xml).toContain('<property name="resource">0</property>');
  });
});
