// Generate the Tauri action manifest the local app consumes — the committed
// artifact for the Move-3F "generate Tauri invoke-command descriptors / capability
// inputs from action metadata" deliverable. Re-run after changing the registry:
//   bun scripts/gen-tauri-actions.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { projectTauriActions } from "../src/actions/tauri-projection";

const actions = projectTauriActions();
const manifest = {
  // A static description of how the app reaches every registered action.
  note: "Generated by scripts/gen-tauri-actions.ts from the vean action registry. Do not edit by hand.",
  command: "run_action",
  count: actions.length,
  actions,
};

const out = join(import.meta.dirname, "..", "app", "src-tauri", "vean-actions.json");
writeFileSync(out, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`wrote ${actions.length} Tauri action descriptors → ${out}`);
