#!/usr/bin/env bun
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const repo = resolve(import.meta.dirname, "..");
const policyArg = process.argv.indexOf("--policy-draft");
if (policyArg < 0 || !process.argv[policyArg + 1]) {
  throw new Error("--policy-draft <path> is required; goldens are never generated by acceptance");
}
const policyPath = resolve(repo, process.argv[policyArg + 1] as string);
const policy = JSON.parse(readFileSync(policyPath, "utf8")) as {
  status?: string;
  parity_case?: { master_frames?: number[]; expected_local_frames?: Array<number | null> };
};
if (policy.status !== "draft")
  throw new Error("generation only accepts an explicitly draft policy");

const fixtureRoot = join(repo, "corpus/harness/media");
const candidate = join(fixtureRoot, "candidate-goldens");
rmSync(candidate, { recursive: true, force: true });
mkdirSync(candidate, { recursive: true });

function hash(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}
function run(argv: string[], cwd = repo): void {
  const result = Bun.spawnSync(argv, { cwd, stdout: "pipe", stderr: "pipe" });
  if (result.exitCode !== 0) throw new Error(`${argv.join(" ")}\n${result.stderr.toString()}`);
}

const frames = policy.parity_case?.master_frames ?? [];
const locals = policy.parity_case?.expected_local_frames ?? [];
const generated: Array<Record<string, unknown>> = [];
const props = {
  title: "vean",
  subtitle: "video editor, agent native",
  accent: "#c7ae7a",
  barColor: "#11131aee",
};
const canonicalProps = `${JSON.stringify(props, null, 2)}\n`;
const propsPath = join(candidate, "canonical-props.json");
writeFileSync(propsPath, canonicalProps);
const xml = (value: string) =>
  value.replaceAll("&", "&amp;").replaceAll('"', "&quot;").replaceAll("<", "&lt;");
for (let index = 0; index < frames.length; index++) {
  const masterFrame = frames[index] as number;
  const localFrame = locals[index] ?? null;
  if (localFrame == null) {
    generated.push({ master_frame: masterFrame, local_frame: null, expected_presence: false });
    continue;
  }
  const path = join(candidate, `base-master-${masterFrame}.png`);
  run([
    "ffmpeg",
    "-hide_banner",
    "-loglevel",
    "error",
    "-y",
    "-i",
    join(fixtureRoot, "assets/proxy-avc.mp4"),
    "-vf",
    `select=eq(n\\,${Math.min(masterFrame, 59)})`,
    "-frames:v",
    "1",
    path,
  ]);
  const remotionPath = join(candidate, `remotion-master-${masterFrame}.png`);
  run(
    [
      "bunx",
      "remotion",
      "still",
      "src/index.ts",
      "LowerThird",
      remotionPath,
      `--frame=${localFrame}`,
      `--props=${JSON.stringify(props)}`,
    ],
    join(repo, "remotion"),
  );
  const mltPath = join(candidate, `mlt-master-${masterFrame}.mlt`);
  const mltPng = join(candidate, `mlt-master-${masterFrame}.png`);
  writeFileSync(
    mltPath,
    `<?xml version="1.0" encoding="utf-8"?>
<mlt LC_NUMERIC="C" root="" title="H07 candidate parity ${masterFrame}">
  <profile width="1080" height="1920" progressive="1" frame_rate_num="30" frame_rate_den="1" sample_aspect_num="1" sample_aspect_den="1" display_aspect_num="9" display_aspect_den="16" colorspace="709"/>
  <producer id="base" in="0" out="0"><property name="mlt_service">color</property><property name="resource">#FF241A52</property><property name="length">1</property></producer>
  <producer id="graphic" in="0" out="0"><property name="mlt_service">qimage</property><property name="resource">${xml(`remotion-master-${masterFrame}.png`)}</property><property name="length">1</property></producer>
  <tractor id="main"><track producer="base"/><track producer="graphic"/><transition mlt_service="qtblend" in="0" out="0"><property name="a_track">0</property><property name="b_track">1</property></transition></tractor>
</mlt>
`,
  );
  run(
    [
      "melt",
      mltPath,
      "in=0",
      "out=0",
      "-consumer",
      `avformat:${mltPng}`,
      "vcodec=png",
      "frames=1",
      "update=1",
    ],
    candidate,
  );
  const mltSha256 = hash(mltPath);
  rmSync(mltPath);
  generated.push({
    master_frame: masterFrame,
    local_frame: localFrame,
    expected_presence: true,
    relative_path: `candidate-goldens/base-master-${masterFrame}.png`,
    sha256: hash(path),
    byte_length: statSync(path).size,
    semantic_markers: {
      exact_presence_boundary: true,
      frame_mapping: masterFrame - 30 === localFrame,
      nonblank_base: statSync(path).size > 100,
    },
    remotion_renderstill: {
      relative_path: `candidate-goldens/remotion-master-${masterFrame}.png`,
      sha256: hash(remotionPath),
      byte_length: statSync(remotionPath).size,
    },
    mlt_still: {
      relative_path: `candidate-goldens/mlt-master-${masterFrame}.png`,
      sha256: hash(mltPng),
      byte_length: statSync(mltPng).size,
      mlt_sha256: mltSha256,
    },
  });
}
const manifestPath = join(candidate, "manifest.json");
writeFileSync(
  manifestPath,
  `${JSON.stringify(
    {
      schema_version: "1.0.0",
      status: "candidate-unapproved",
      acceptance_eligible: false,
      policy_sha256: hash(policyPath),
      fixture_manifest_sha256: hash(join(fixtureRoot, "manifest.json")),
      canonical_props_sha256: hash(propsPath),
      composition_source_sha256: hash(join(repo, "remotion/src/compositions/LowerThird.tsx")),
      remotion_package_sha256: hash(join(repo, "remotion/package.json")),
      viewer_package_sha256: hash(join(repo, "viewer/package.json")),
      generator: { path: "scripts/media-goldens.ts", sha256: hash(import.meta.filename) },
      frames: generated,
    },
    null,
    2,
  )}\n`,
);
run(["bunx", "biome", "format", "--write", manifestPath]);
console.log(
  JSON.stringify({
    status: "candidate-generated",
    manifestPath,
    manifestSha256: hash(manifestPath),
  }),
);
