#!/usr/bin/env bun
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { generateRenderTruth } from "./media-render-truth";

const repo = resolve(import.meta.dirname, "..");
const policyArg = process.argv.indexOf("--policy-draft");
if (policyArg < 0 || !process.argv[policyArg + 1]) {
  throw new Error("--policy-draft <path> is required; goldens are never generated by acceptance");
}
const policyPath = resolve(repo, process.argv[policyArg + 1] as string);
const policy = JSON.parse(readFileSync(policyPath, "utf8")) as { status?: string };
if (policy.status !== "draft")
  throw new Error("generation only accepts an explicitly draft policy");

const result = await generateRenderTruth({
  outputRoot: resolve(repo, "corpus/harness/media/candidate-goldens"),
  policyPath,
});
const manifestSha256 = createHash("sha256").update(readFileSync(result.manifestPath)).digest("hex");
console.log(
  JSON.stringify({
    status: "candidate-generated",
    manifestPath: result.manifestPath,
    manifestSha256,
  }),
);
