#!/usr/bin/env bun
// verify:premult — the render golden for PREMULTIPLIED-ALPHA compositing (roadmap
// a.3 / the Remotion-seam premultiply check). This is the gate that catches EDGE
// HALOS on overlay graphics: the classic straight-vs-premultiplied-alpha mismatch
// that both Premiere and Resolve guard against, and the named cause of a fringe
// of the wrong colour around anti-aliased overlay edges.
//
//   bun run verify:premult
//
// WHY THIS GATE EXISTS (and what it proves)
//   Remotion + Chromium produce STRAIGHT (unassociated) alpha ProRes 4444. MLT's
//   `qtblend` (Qt QPainter, the compositor `src/actions/graphic.ts` emits) composites
//   with the source-over Porter-Duff operator. The two are only halo-free when MLT
//   honours the STRAIGHT alpha — i.e. multiplies the overlay RGB by its own alpha at
//   composite time, so the transparent-region RGB NEVER leaks into the edge. If a
//   regression ever (a) double-premultiplies, or (b) ignores the alpha and shows the
//   raw RGB, an anti-aliased edge develops a coloured fringe. `verify:graphic` proves
//   footage shows THROUGH transparency; this gate proves the EDGE is clean.
//
//   The test is a POISON overlay — a ProRes 4444 alpha clip where:
//     • the foreground (a centred disk) RGB is defined THROUGH the anti-aliased
//       alpha edge (clean straight-alpha authoring: white wherever alpha > 0), and
//     • the FULLY-TRANSPARENT region (alpha = 0) RGB is a bright MAGENTA poison.
//   A correct premultiplied-honouring composite over BLUE footage blends the white
//   disk smoothly to blue across the AA band and the magenta NEVER appears. A halo
//   shows up as a magenta (poison-leak) OR an over-dark (double-premultiply) fringe
//   at the edge — both measured here, both a hard FAIL. (Empirically, a real
//   mismatch produces a poison-leak of ~220 on this fixture; a clean composite ~18.)
//
// WHAT IS COMMITTED vs REGENERATED (matches verify:graphic / verify:move5)
//   committed   : THIS script + the deterministic composite IR it builds in-memory.
//   regenerated : the poison `.mov` (gitignored `*.mov`) — self-generated by ffmpeg,
//                 so the gate has no committed binary dependency.
//
// A failure to render or MEASURE is a hard FAIL (never a silent pass), exactly like
// verify:corpus / verify:graphic. Requires `melt` + `ffmpeg` + `ffprobe` on PATH.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { addGraphic } from "../src/actions/graphic";
import { still } from "../src/driver/melt";
import { colorClip, resetIds, timeline, videoTrack } from "../src/ir/builder";
import { fromMlt } from "../src/ir/parse";
import { SQUARE, VERTICAL } from "../src/ir/profile";
import { toMlt } from "../src/ir/serialize";
import { apply } from "../src/ops";
import { isEditError } from "../src/ops/types";

const ROOT = resolve(import.meta.dirname, "..");
const OUT = join(ROOT, "out", "verify-premult");

// The square demo profile (1080×1080 @30) — so the overlay AA edge is the whole
// subject and the still is cheap to scan. The overlay is generated at this size.
const W = SQUARE.width; // 1080
const H = SQUARE.height; // 1080
const CX = W / 2;
const CY = H / 2;
// The disk: opaque inside R_SOLID, an ANTI-ALIASED fade R_SOLID..R_EDGE, transparent
// beyond. The AA band is where a premultiply mismatch leaks a fringe.
const R_SOLID = 300;
const R_EDGE = 360;
const FRAME = 0;

const POISON_DESC = "magenta (R,B high, G≈0) — must NEVER appear at the edge";

/** POSIX single-quote escape for a path embedded in a `sh -c` command. */
function sh(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

/** Build the POISON overlay (no committed binary): a white disk whose RGB is
 *  defined THROUGH the anti-aliased alpha edge, on a MAGENTA fully-transparent
 *  background, encoded ProRes 4444 with a straight-alpha plane. Asserts the encoded
 *  clip carries `yuva*` (a clip without alpha would make the gate meaningless). */
function makePoisonOverlay(path: string): void {
  const dur = "1";
  const hyp = `hypot(X-${CX},Y-${CY})`;
  // RGB plane: white (255,255,255) where alpha>0 (disk r<R_EDGE), MAGENTA (255,0,255)
  // in the transparent region. The disk RGB extends THROUGH the AA band so a correct
  // straight composite blends white→footage, never magenta.
  const rgb = `color=c=black:s=${W}x${H}:r=30:d=${dur},format=gbrp,geq=r='255':g='if(lt(${hyp},${R_EDGE}),255,0)':b='255'`;
  // Alpha plane: opaque r<R_SOLID, linear AA fade R_SOLID..R_EDGE, transparent beyond.
  const alpha = `color=c=black:s=${W}x${H}:r=30:d=${dur},format=gray,geq=lum='if(lt(${hyp},${R_SOLID}),255,if(lt(${hyp},${R_EDGE}),255*(${R_EDGE}-${hyp})/(${R_EDGE}-${R_SOLID}),0))'`;
  // One ffmpeg command line, assembled from labelled segments (joined, never
  // concatenated into one collapsible template — keeps the linter happy).
  const cmd = [
    "ffmpeg -hide_banner -loglevel error -y",
    `-f lavfi -i "${rgb}"`,
    `-f lavfi -i "${alpha}"`,
    `-filter_complex "[0][1]alphamerge,format=yuva444p10le"`,
    "-c:v prores_ks -profile:v 4444 -pix_fmt yuva444p10le",
    sh(path),
  ].join(" ");
  execFileSync("sh", ["-c", cmd], { encoding: "utf8" });

  const pixFmt = execFileSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-select_streams",
      "v:0",
      "-show_entries",
      "stream=pix_fmt",
      "-of",
      "default=nw=1:nk=1",
      path,
    ],
    { encoding: "utf8" },
  ).trim();
  if (!pixFmt.includes("yuva")) {
    throw new Error(
      `poison overlay has NO alpha plane (${pixFmt}); the premult gate would be meaningless`,
    );
  }
}

/** Decode the whole composited PNG once into a flat rgb24 buffer (W*H*3) and index
 *  it directly — melt writes a 4:2:0 PNG that ffmpeg's per-pixel `crop` rejects, so
 *  a single whole-frame decode is the robust path (manual bisection found this). */
function readRgb24(png: string): Uint8Array {
  const raw = join(OUT, "composite.raw");
  execFileSync(
    "sh",
    [
      "-c",
      `ffmpeg -hide_banner -loglevel error -y -i ${sh(png)} -f rawvideo -pix_fmt rgb24 ${sh(raw)}`,
    ],
    { encoding: "utf8" },
  );
  return new Uint8Array(readFileSync(raw));
}

type Rgb = { r: number; g: number; b: number };
function pixel(buf: Uint8Array, x: number, y: number): Rgb {
  const o = (y * W + x) * 3;
  return { r: buf[o] ?? 0, g: buf[o + 1] ?? 0, b: buf[o + 2] ?? 0 };
}

/** Composite the REAL Remotion lower-third over a BRIGHT footage base and assert
 *  its transparent regions stay clean (the footage shows through, undarkened by a
 *  premultiply-mismatch fringe). The overlay's fully-transparent RGB is black
 *  `(0,0,0,0)`, so a straight-vs-premultiplied mismatch would darken the footage in
 *  the transparent region — measured here as the footage's GREEN channel dropping.
 *  Returns the list of failures (empty = clean). Renders at the VERTICAL profile the
 *  overlay was authored for (1080×1920 — same width as SQUARE, so `pixel` indexes it
 *  too). */
async function checkRealLowerThird(overlay: string): Promise<string[]> {
  const fails: string[] = [];
  resetIds();
  // Bright GREEN footage (#FF00FF00), 90 frames — long enough to span the overlay,
  // so the overlay's transparent regions have footage to reveal at frame 60. A
  // transparent-region darkening shows as the green channel dropping below the base.
  const REAL_DUR = 90;
  const footage = colorClip(REAL_DUR, "#FF00FF00");
  const base = timeline(VERTICAL, { video: [videoTrack(footage)] });
  const res = addGraphic(base, {
    clipPath: overlay,
    position: 0,
    durationFrames: 90,
    newTrack: true,
  });
  if (!("state" in res)) {
    fails.push(`real lower-third: addGraphic errored: ${JSON.stringify(res)}`);
    return fails;
  }
  const mlt = join(OUT, "real-lt.mlt");
  writeFileSync(mlt, toMlt(res.state));
  const png = join(OUT, "real-lt-f60.png");
  // Frame 60 — mid-animation, the bar + accent stripe are fully on screen.
  const r = await still(mlt, 60, png);
  if (r.code !== 0) {
    fails.push(`real lower-third: melt still failed (code ${r.code}):\n${r.stderr.slice(-300)}`);
    return fails;
  }
  const buf = readRgb24(png);
  // Sample the upper third (well above the lower-third bar) — a fully-transparent
  // overlay region. The bright green footage MUST show through cleanly (green
  // dominant, not darkened toward black by a transparent-region premultiply fringe).
  const top = pixel(buf, Math.round(VERTICAL.width / 2), 200);
  console.log(
    `\nreal lower-third over green footage — transparent region (540,200) rgb(${top.r},${top.g},${top.b})`,
  );
  if (top.g < 150 || top.r > 90 || top.b > 90) {
    fails.push(
      `real lower-third: the overlay's TRANSPARENT region darkened/tinted the footage (expected bright green, got rgb(${top.r},${top.g},${top.b})) — a straight-vs-premultiplied mismatch on the production overlay.`,
    );
  } else {
    console.log(
      "ok    real lower-third transparent region shows the footage cleanly (no dark fringe)",
    );
  }
  return fails;
}

async function main(): Promise<void> {
  mkdirSync(OUT, { recursive: true });

  // 1) The poison overlay (white disk through AA edge + MAGENTA transparent RGB).
  const overlay = join(OUT, "poison-overlay.mov");
  makePoisonOverlay(overlay);

  // 2) Composite over OPAQUE BLUE footage through the REAL addGraphic action — the
  //    exact path the CLI/MCP take (qtblend over-composite). `colorClip` is the
  //    synthesized footage stand-in (no external asset; the AA edge is the subject).
  resetIds();
  const footage = colorClip(2, "#FF0000FF"); // #AARRGGBB → opaque BLUE
  const original = timeline(SQUARE, { video: [videoTrack(footage)] });

  const result = addGraphic(original, {
    clipPath: overlay,
    position: 0,
    durationFrames: 1,
    newTrack: true,
  });
  if (!("state" in result)) {
    console.error(`FAIL  addGraphic returned an error: ${JSON.stringify(result)}`);
    process.exit(1);
  }

  const mlt = join(OUT, "composite.mlt");
  writeFileSync(mlt, toMlt(result.state));

  // 3) Render the still and scan the ANTI-ALIASED EDGE band for a halo.
  const png = join(OUT, `composite-f${FRAME}.png`);
  const r = await still(mlt, FRAME, png);
  if (r.code !== 0) {
    console.error(`FAIL  melt still failed (code ${r.code}):\n${r.stderr.slice(-400)}`);
    process.exit(1);
  }
  const buf = readRgb24(png);

  // Scan a radial line from just inside the AA band to just past it. Measure, per
  // pixel, the POISON LEAK = min(R,B) - G (magenta dominant ⇒ the transparent RGB
  // leaked into the edge — the straight-vs-premultiplied halo). Track the WORST
  // pixel inline so the failure message can name the exact offending coordinate.
  let worstLeak = 0;
  let worstX = Math.round(CX + R_SOLID);
  let worstPx: Rgb = pixel(buf, worstX, CY);
  for (let rr = R_SOLID - 8; rr <= R_EDGE + 12; rr++) {
    const x = Math.round(CX + rr);
    const px = pixel(buf, x, CY);
    const leak = Math.min(px.r, px.b) - px.g;
    if (leak > worstLeak) {
      worstLeak = leak;
      worstX = x;
      worstPx = px;
    }
  }

  const interior = pixel(buf, Math.round(CX), CY); // the opaque white disk
  const base = pixel(buf, 20, 20); // the opaque blue footage
  // The AA midpoint (alpha ≈ 0.5): a correct straight composite is BRIGHT white-ish;
  // a double-premultiply collapses it toward the base. The threshold is content-
  // relative (a fraction of the way from base→disk), not a magic number.
  const mid = pixel(buf, Math.round(CX + (R_SOLID + R_EDGE) / 2), CY);
  const midLuma = mid.r + mid.g + mid.b;
  const interiorLuma = interior.r + interior.g + interior.b;
  const baseLuma = base.r + base.g + base.b;
  const expectedMidFloor = baseLuma + 0.3 * (interiorLuma - baseLuma);

  console.log(
    `interior disk (${Math.round(CX)},${CY})  rgb(${interior.r},${interior.g},${interior.b})`,
  );
  console.log(`footage base  (20,20)                   rgb(${base.r},${base.g},${base.b})`);
  console.log(
    `AA midpoint   (${Math.round(CX + (R_SOLID + R_EDGE) / 2)},${CY})  rgb(${mid.r},${mid.g},${mid.b})  luma=${midLuma}  (floor ${Math.round(expectedMidFloor)})`,
  );
  console.log(`worst poison-leak across the edge = ${worstLeak}   (poison = ${POISON_DESC})`);

  const failures: string[] = [];
  // (a) POISON LEAK — the transparent-region RGB bled into the edge (the classic
  // halo). A small residual is the blue base bleeding; a real leak is large.
  if (worstLeak > 40) {
    failures.push(
      `EDGE HALO: the overlay's transparent-region poison RGB leaked into the anti-aliased edge (worst magenta-fringe ${worstLeak} at x=${worstX}, rgb(${worstPx.r},${worstPx.g},${worstPx.b})). This is the straight-vs-premultiplied-alpha mismatch — MLT is not compositing the ProRes 4444 alpha as premultiplied.`,
    );
  }
  // (b) DOUBLE-PREMULTIPLY — the AA midpoint collapsed toward the base (an over-dark
  // fringe). Only meaningful if the disk is actually brighter than the base.
  if (interiorLuma > baseLuma + 60 && midLuma < expectedMidFloor) {
    failures.push(
      `EDGE HALO: the anti-aliased edge is OVER-DARK (midpoint luma ${midLuma} < floor ${Math.round(expectedMidFloor)}) — the overlay RGB appears DOUBLE-premultiplied (multiplied by alpha twice), darkening the soft edge.`,
    );
  }

  // 4) The composite is reversible — the inverse reconstructs the original IR.
  let work = result.state;
  for (const inv of result.inverse) {
    const back = apply(inv, work);
    if (isEditError(back)) {
      failures.push(`inverse step errored: ${JSON.stringify(back)}`);
      break;
    }
    work = back.state;
  }
  if (JSON.stringify(work) !== JSON.stringify(original)) {
    failures.push("inverse did not reconstruct the original IR exactly");
  }

  // 5) The serialized composite is a round-trip fixpoint (no determinism drift).
  const a = toMlt(fromMlt(toMlt(result.state)));
  const b = toMlt(fromMlt(a));
  if (a !== b) failures.push("serialized composite is not a round-trip fixpoint");

  // 6) The REAL Remotion lower-third (the roadmap's named fixture: "Remotion
  //    lower-third over footage"). The synthetic poison overlay above is the
  //    discriminating probe; this asserts the ACTUAL production overlay
  //    (corpus/demo/lower-third.mov, rendered by `bun run demo:build`) composites
  //    halo-free over footage through the same qtblend path. SKIPPED when the
  //    gitignored `.mov` is absent (a fresh clone), so the gate still passes there.
  const realOverlay = join(ROOT, "corpus", "demo", "lower-third.mov");
  if (existsSync(realOverlay)) {
    const realFails = await checkRealLowerThird(realOverlay);
    failures.push(...realFails);
  } else {
    console.log(
      `\nskip  real lower-third check (no ${realOverlay} — run \`bun run demo:build\` to render it)`,
    );
  }

  console.log("");
  if (failures.length === 0) {
    console.log(
      "OVERALL: PASS — the ProRes 4444 alpha composites as PREMULTIPLIED: the anti-aliased edge is " +
        "halo-free (no poison leak, no double-dark fringe), and the composite is reversible + deterministic.",
    );
    process.exit(0);
  }
  for (const f of failures) console.log(`FAIL  ${f}`);
  console.log(`\nOVERALL: FAIL — ${failures.length} premultiplied-alpha defect(s).`);
  process.exit(1);
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(err instanceof Error ? err.stack : err);
    process.exit(1);
  });
}
